/**
 * Builds the derived web stylesheet — the `theme.css` in the export bundle.
 *
 * A pure function of builder state, deliberately not inlined in `useExport`: it
 * is the artifact most consumers actually ship, so it needs to be testable
 * without a React renderer. `buildConfig.test.ts` asserts it declares every token
 * `@ui-organized/react` consumes.
 */

import { resolveSemanticColors } from "@ui-organized/utils";
import {
  computeTypographyVars,
  computeSpacingVars,
  computeRadiusVars,
  computeComponentTokenVars,
  computeControlHeightVars,
  computeGlobalConstantVars,
  type CSSVarMap,
} from "./semanticMapping";
import type { BuilderState } from "../state/themeState";

/**
 * The stylesheet's name inside the zip.
 *
 * Deliberately fixed rather than slugified from the theme name: every snippet in
 * the bundle README, the export panel and the docs says `theme.css`, and a file
 * that arrives called `kitchen-sink-teal.css` makes all of them wrong. The zip
 * itself still carries the theme's name.
 */
export const CSS_FILENAME = "theme.css";

function block(selector: string, vars: CSSVarMap): string {
  const body = Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${body}\n}`;
}

/**
 * Build a self-contained theme stylesheet from the current builder state.
 *
 * Layout:
 *   :root                 → the default mode's semantic colors + every
 *                           mode-independent token (typography, spacing, radius,
 *                           component aliases, layout constants)
 *   [data-theme="light"]  → light semantic colors
 *   [data-theme="dark"]   → dark semantic colors
 *
 * All three selectors have identical specificity, so the mode blocks win on
 * source order — which is also why this file must be imported *after* any
 * baseline token stylesheet, not merely after the component styles.
 *
 * Colors resolve against the chosen brand and neutral families through the same
 * `resolveSemanticColors` source of truth the live preview uses. The layout
 * constants come from `@ui-organized/tokens`. Emitting them is not optional: the
 * component CSS reads `--dimension-06` and the `--z-index-*` stack, and a
 * stylesheet that omits them produces a green build, a clean console, a sidebar
 * silently shrunk to fit and every overlay stacking on DOM order alone.
 */
export function buildThemeCss(state: BuilderState): string {
  const colorOpts = {
    brandRamp: state.brandRamp,
    neutralRamp: state.neutralRamp,
    brandShade: state.brandShade,
  };
  const light = resolveSemanticColors("light", colorOpts);
  const dark = resolveSemanticColors("dark", colorOpts);
  const byMode = { light, dark };

  const nonColor: CSSVarMap = {
    ...computeTypographyVars(
      state.headingFamily,
      state.bodyFamily,
      state.headingWeights,
      state.bodyWeights,
      state.typeScaleSteps,
      state.leadingSteps,
    ),
    ...computeSpacingVars(state.spacingScale),
    ...computeRadiusVars(state.borderRadius),
    ...computeComponentTokenVars(state.borderRadius, state.spacingScale),
    ...computeControlHeightVars(state.leadingSteps, state.spacingScale),
    ...computeGlobalConstantVars(),
  };

  const defaultMode = state.exportDefaultMode;
  const rootMode = defaultMode === "system" ? "light" : defaultMode;

  const header =
    `/* ${state.themeName || "My Theme"} — generated by the UI Organized Theme Builder.\n` +
    `   Brand: ${state.brandMode === "custom" ? `custom ${state.brandHex}` : state.brandFamily} · ` +
    `Neutral: ${state.neutralFamily} · Primary shade: ${state.brandShade}\n` +
    `   Default mode: ${defaultMode}${defaultMode === "system" ? " — follows prefers-color-scheme" : ""}.\n` +
    `   Import AFTER @ui-organized/react/styles so this wins on source order. */\n`;

  const blocks = [header, block(":root", { ...byMode[rootMode], ...nonColor })];

  if (defaultMode === "system") {
    // `:not([data-theme])` is what keeps an explicit attribute authoritative.
    // Without it this rule ties with `[data-theme="light"]` on specificity and
    // wins on source order, so a light island inside a dark OS theme goes dark.
    const decls = Object.entries(dark)
      .map(([k, v]) => `    ${k}: ${v};`)
      .join("\n");
    blocks.push(
      `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n${decls}\n  }\n}`,
    );
  }

  blocks.push(block('[data-theme="light"]', light), block('[data-theme="dark"]', dark));
  return blocks.join("\n\n") + "\n";
}
