/**
 * Canonical semantic color mapping (dark + light), reference-based.
 * GENERATED from the design-system token JSON
 * (packages/tokens/src/semantic + src/themes/light) — the same source the
 * shipped library CSS is built from. This is the single source of truth the
 * builder uses for both live preview and theme export.
 *
 * Each value is either:
 *   - a primitive reference "family.step" (e.g. "brand.1400", "grey.2300",
 *     "crimson.1500"), resolved against the chosen brand/neutral families, or
 *   - a raw CSS value (e.g. "#007dde", "rgba(...)") passed through unchanged.
 *
 * "brand.*" resolves to the selected brand family; "grey.*" resolves to the
 * selected neutral family; any other family resolves to its fixed core ramp.
 */

export type SemanticRefMap = Record<string, string>;

export const semanticColorMap: { dark: SemanticRefMap; light: SemanticRefMap } = {
  dark: {
    "--color-border-primary": "grey.2100",
    "--color-border-secondary": "grey.2000",
    "--color-border-data-entry": "grey.1900",
    "--color-interactive-primary-default": "brand.1400",
    "--color-interactive-primary-hover": "brand.1600",
    "--color-interactive-primary-active": "brand.1300",
    "--color-interactive-primary-selected": "brand.1400",
    "--color-interactive-secondary-default": "#ffffff",
    "--color-interactive-secondary-hover": "#ffffff",
    "--color-interactive-secondary-active": "#ffffff",
    "--color-interactive-secondary-selected": "#ffffff",
    "--color-interactive-tertiary-default": "brand.1100",
    "--color-interactive-tertiary-hover": "brand.1600",
    "--color-interactive-tertiary-active": "brand.1300",
    "--color-interactive-tertiary-selected": "brand.1000",
    "--color-interactive-ghost-default": "#fcfcfc",
    "--color-interactive-ghost-hover": "#ffffff",
    "--color-interactive-ghost-active": "#ffffff",
    "--color-interactive-destructive-default": "crimson.1500",
    "--color-interactive-destructive-default-ghost": "crimson.1100",
    "--color-interactive-destructive-hover": "crimson.1700",
    "--color-interactive-destructive-active": "crimson.1400",
    "--color-interactive-contents": "grey.100",
    "--color-interactive-ui-default": "grey.100",
    "--color-interactive-ui-hover": "grey.100",
    "--color-interactive-ui-active": "grey.100",
    "--color-interactive-ui-selected": "grey.100",
    "--color-interactive-ui-inverse": "grey.1200",
    "--color-interactive-ui-light": "grey.100",
    "--color-interactive-ui-dark": "grey.2400",
    "--color-interactive-focus": "grey.100",
    "--color-interactive-focus-inverse": "grey.2400",
    "--color-interactive-inactive-01": "grey.2000",
    "--color-interactive-inactive-02": "grey.1800",
    "--color-interactive-inactive-03": "grey.1600",
    "--color-icon-primary": "grey.100",
    "--color-icon-secondary": "grey.500",
    "--color-icon-tertiary": "grey.900",
    "--color-icon-light": "grey.100",
    "--color-icon-dark": "grey.2400",
    "--color-status-success": "lima.1600",
    "--color-status-success-bg": "lima.2100",
    "--color-status-success-content": "lima.500",
    "--color-status-info": "cerulean.1600",
    "--color-status-info-bg": "cerulean.2100",
    "--color-status-info-content": "cerulean.500",
    "--color-status-info-secondary": "caribbean.1600",
    "--color-status-info-secondary-bg": "caribbean.2100",
    "--color-status-info-secondary-content": "caribbean.500",
    "--color-status-caution": "candlelight.1600",
    "--color-status-caution-bg": "candlelight.2100",
    "--color-status-caution-content": "candlelight.500",
    "--color-status-warning": "cerise.1600",
    "--color-status-warning-bg": "cerise.2100",
    "--color-status-warning-content": "cerise.500",
    "--color-status-error": "crimson.1600",
    "--color-status-error-message": "crimson.1400",
    "--color-status-error-bg": "crimson.2100",
    "--color-status-error-content": "crimson.500",
    "--color-surface-base": "grey.2400",
    "--color-surface-primary": "grey.2300",
    "--color-surface-secondary": "grey.2200",
    "--color-surface-overlay-primary": "grey.100",
    "--color-surface-overlay-secondary": "grey.100",
    "--color-surface-overlay-tertiary": "grey.100",
    "--color-surface-curtain": "rgba(0, 0, 0, 0.8)",
    "--color-text-primary": "grey.100",
    "--color-text-secondary": "grey.500",
    "--color-text-tertiary": "grey.900",
    "--color-text-placeholder": "grey.1400",
    "--color-text-inverse": "grey.2400",
    "--color-text-dark": "grey.2400",
    "--color-text-light": "grey.100"
  },
  light: {
    "--color-border-primary": "grey.800",
    "--color-border-secondary": "grey.500",
    "--color-border-data-entry": "grey.1600",
    "--color-interactive-primary-default": "brand.1400",
    "--color-interactive-primary-hover": "brand.1600",
    "--color-interactive-primary-active": "brand.1300",
    "--color-interactive-primary-selected": "brand.1300",
    "--color-interactive-secondary-default": "#000000",
    "--color-interactive-secondary-hover": "#000000",
    "--color-interactive-secondary-active": "#000000",
    "--color-interactive-secondary-selected": "#000000",
    "--color-interactive-tertiary-default": "brand.1500",
    "--color-interactive-tertiary-hover": "brand.1600",
    "--color-interactive-tertiary-active": "brand.1300",
    "--color-interactive-tertiary-selected": "brand.1000",
    "--color-interactive-ghost-default": "#fcfcfc",
    "--color-interactive-ghost-hover": "#000000",
    "--color-interactive-ghost-active": "#000000",
    "--color-interactive-destructive-default": "crimson.1400",
    "--color-interactive-destructive-default-ghost": "crimson.1400",
    "--color-interactive-destructive-hover": "crimson.1200",
    "--color-interactive-destructive-active": "crimson.1300",
    "--color-interactive-contents": "grey.100",
    "--color-interactive-ui-default": "#020202",
    "--color-interactive-ui-hover": "#020202",
    "--color-interactive-ui-active": "#020202",
    "--color-interactive-ui-selected": "#020202",
    "--color-interactive-ui-inverse": "grey.1600",
    "--color-interactive-ui-light": "grey.100",
    "--color-interactive-ui-dark": "grey.2400",
    "--color-interactive-focus": "grey.2400",
    "--color-interactive-focus-inverse": "grey.100",
    "--color-interactive-inactive-01": "grey.1400",
    "--color-interactive-inactive-02": "grey.1000",
    "--color-interactive-inactive-03": "grey.800",
    "--color-icon-primary": "grey.2400",
    "--color-icon-secondary": "grey.2000",
    "--color-icon-tertiary": "grey.1600",
    "--color-icon-light": "grey.100",
    "--color-icon-dark": "grey.2400",
    "--color-status-success": "lima.1000",
    "--color-status-success-bg": "lima.500",
    "--color-status-success-content": "lima.2100",
    "--color-status-info": "cerulean.1000",
    "--color-status-info-bg": "cerulean.500",
    "--color-status-info-content": "cerulean.2100",
    "--color-status-info-secondary": "caribbean.1000",
    "--color-status-info-secondary-bg": "caribbean.500",
    "--color-status-info-secondary-content": "caribbean.2100",
    "--color-status-caution": "candlelight.1300",
    "--color-status-caution-bg": "candlelight.500",
    "--color-status-caution-content": "candlelight.2100",
    "--color-status-warning": "cerise.1000",
    "--color-status-warning-bg": "cerise.500",
    "--color-status-warning-content": "cerise.2100",
    "--color-status-error": "crimson.1000",
    "--color-status-error-message": "crimson.1600",
    "--color-status-error-bg": "crimson.500",
    "--color-status-error-content": "crimson.2100",
    "--color-surface-base": "grey.400",
    "--color-surface-primary": "grey.100",
    "--color-surface-secondary": "grey.300",
    "--color-surface-overlay-primary": "#020202",
    "--color-surface-overlay-secondary": "#020202",
    "--color-surface-overlay-tertiary": "#020202",
    "--color-surface-curtain": "rgba(0, 0, 0, 0.8)",
    "--color-text-primary": "grey.2400",
    "--color-text-secondary": "grey.2000",
    "--color-text-tertiary": "grey.1600",
    "--color-text-placeholder": "grey.1400",
    "--color-text-inverse": "grey.100",
    "--color-text-dark": "grey.2400",
    "--color-text-light": "grey.100"
  },
};
