/**
 * The block layer of markdown, for text authored as markdown elsewhere.
 *
 * `InlineMarkdown` covers what a one-line prop description needs. Changelog
 * entries are a different shape: Changesets bodies in this repo run to several
 * paragraphs with fenced code, sub-bullets and the occasional table, and
 * dropping those into JSX raw shows the reader literal backtick fences.
 *
 * Still not a markdown library. The input is generated by Changesets from files
 * authored in this repo, so the subset is known and small — and rendering it
 * ourselves is what lets a fenced block come out as the docs kit's own
 * `CodeBlock`, with the themed frame and the copy button every other snippet on
 * the site has, rather than as a foreign `<pre>`. Inline spans delegate to
 * `renderInline`, so bold and code look identical here and in a prop table.
 *
 * Everything is rendered as React elements — no `dangerouslySetInnerHTML`, so
 * no sanitiser is needed even though the text comes from source files.
 * Constructs outside the subset (HTML, images, footnotes) fall through as
 * plain text rather than disappearing.
 */
import { Fragment, type ReactNode } from "react";
import { CodeBlock } from "./CodeBlock";
import { renderInline } from "./InlineMarkdown";
import styles from "./content.module.css";

interface ListItem {
  text: string;
  children: string[];
}

type Block =
  | { kind: "paragraph"; text: string }
  | { kind: "heading"; text: string }
  | { kind: "code"; code: string; language: string }
  | { kind: "list"; ordered: boolean; items: ListItem[] }
  | { kind: "table"; head: string[]; rows: string[][] }
  | { kind: "quote"; text: string };

const FENCE = /^```(\S*)\s*$/;
const HEADING = /^#{1,6}\s+(.+?)\s*$/;
const BULLET = /^[-*]\s+(.*)$/;
const ORDERED = /^\d+[.)]\s+(.*)$/;
/** A nested bullet — two spaces of indent is what Changesets sub-lists use. */
const NESTED_BULLET = /^\s{2,}[-*]\s+(.*)$/;
const QUOTE = /^>\s?(.*)$/;
/** GFM's `| --- | :--: |` separator, which is what makes a pipe row a table. */
const TABLE_RULE = /^\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?$/;

/** `| a | b |` → `["a", "b"]`. Cells never contain a pipe in this content. */
function splitRow(line: string): string[] {
  return line
    .replace(/^\s*\|/, "")
    .replace(/\|\s*$/, "")
    .split("|")
    .map((cell) => cell.trim());
}

function isPipeRow(line: string): boolean {
  return line.trim().startsWith("|");
}

export function parseBlocks(markdown: string): Block[] {
  const lines = markdown.split("\n");
  const blocks: Block[] = [];
  let index = 0;

  while (index < lines.length) {
    const line = lines[index];

    if (line.trim() === "") {
      index += 1;
      continue;
    }

    // ── Fenced code ─────────────────────────────────────────────────────────
    const fence = FENCE.exec(line);
    if (fence) {
      const body: string[] = [];
      index += 1;
      while (index < lines.length && !FENCE.test(lines[index])) {
        body.push(lines[index]);
        index += 1;
      }
      // Step past the closing fence. An unterminated block just ends with the
      // text, which is better than swallowing the rest of the entry.
      index += 1;
      blocks.push({ kind: "code", code: body.join("\n"), language: fence[1] || "text" });
      continue;
    }

    // ── Heading ─────────────────────────────────────────────────────────────
    const heading = HEADING.exec(line);
    if (heading) {
      blocks.push({ kind: "heading", text: heading[1] });
      index += 1;
      continue;
    }

    // ── Table ───────────────────────────────────────────────────────────────
    if (isPipeRow(line) && index + 1 < lines.length && TABLE_RULE.test(lines[index + 1].trim())) {
      const head = splitRow(line);
      const rows: string[][] = [];
      index += 2;
      while (index < lines.length && isPipeRow(lines[index])) {
        rows.push(splitRow(lines[index]));
        index += 1;
      }
      blocks.push({ kind: "table", head, rows });
      continue;
    }

    // ── Blockquote ──────────────────────────────────────────────────────────
    if (QUOTE.test(line)) {
      const body: string[] = [];
      while (index < lines.length && QUOTE.test(lines[index])) {
        body.push(QUOTE.exec(lines[index])![1]);
        index += 1;
      }
      blocks.push({ kind: "quote", text: body.join(" ").trim() });
      continue;
    }

    // ── List ────────────────────────────────────────────────────────────────
    const bullet = BULLET.exec(line);
    const ordered = ORDERED.exec(line);
    if (bullet || ordered) {
      const isOrdered = Boolean(ordered && !bullet);
      const marker = isOrdered ? ORDERED : BULLET;
      const items: ListItem[] = [];

      while (index < lines.length) {
        const current = lines[index];
        const item = marker.exec(current);

        if (item) {
          items.push({ text: item[1], children: [] });
          index += 1;
          continue;
        }

        const nested = NESTED_BULLET.exec(current);
        if (nested && items.length > 0) {
          items[items.length - 1].children.push(nested[1]);
          index += 1;
          continue;
        }

        // A wrapped continuation of the item above — indented, not a new
        // marker, not blank.
        if (items.length > 0 && current.startsWith(" ") && current.trim() !== "") {
          items[items.length - 1].text += ` ${current.trim()}`;
          index += 1;
          continue;
        }

        break;
      }

      blocks.push({ kind: "list", ordered: isOrdered, items });
      continue;
    }

    // ── Paragraph ───────────────────────────────────────────────────────────
    // The first line is taken unconditionally. Everything above has already
    // declined it, and a paragraph that consumed nothing would spin forever —
    // a pipe row with no GFM rule under it reaches here and is prose, but it
    // still satisfies the `isPipeRow` stop condition below.
    const paragraph: string[] = [line.trim()];
    index += 1;

    while (index < lines.length) {
      const current = lines[index];
      if (
        current.trim() === "" ||
        FENCE.test(current) ||
        HEADING.test(current) ||
        QUOTE.test(current) ||
        BULLET.test(current) ||
        ORDERED.test(current) ||
        isPipeRow(current)
      ) {
        break;
      }
      paragraph.push(current.trim());
      index += 1;
    }
    blocks.push({ kind: "paragraph", text: paragraph.join(" ") });
  }

  return blocks;
}

export function MarkdownBlocks({ markdown }: { markdown: string }) {
  return (
    <>
      {parseBlocks(markdown).map((block, index) => (
        <Fragment key={index}>{renderBlock(block)}</Fragment>
      ))}
    </>
  );
}

function renderBlock(block: Block): ReactNode {
  switch (block.kind) {
    case "code":
      return <CodeBlock code={block.code} language={block.language} />;

    // Entry bodies live under the release's own heading, so their internal
    // headings are always sub-headings — the same level and treatment a docs
    // page gives an `<h3>` inside a section.
    case "heading":
      return <h4 className={styles.sectionSub}>{renderInline(block.text)}</h4>;

    case "quote":
      return <blockquote className={styles.quote}>{renderInline(block.text)}</blockquote>;

    case "table":
      return (
        <div className={styles.tableWrap}>
          <table className={styles.table}>
            <thead>
              <tr>
                {block.head.map((cell, index) => (
                  <th key={index}>{renderInline(cell)}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {block.rows.map((row, rowIndex) => (
                <tr key={rowIndex}>
                  {row.map((cell, cellIndex) => (
                    <td key={cellIndex}>{renderInline(cell)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );

    case "list": {
      const List = block.ordered ? "ol" : "ul";
      return (
        <List>
          {block.items.map((item, index) => (
            <li key={index}>
              {renderInline(item.text)}
              {item.children.length > 0 && (
                <ul>
                  {item.children.map((child, childIndex) => (
                    <li key={childIndex}>{renderInline(child)}</li>
                  ))}
                </ul>
              )}
            </li>
          ))}
        </List>
      );
    }

    default:
      return <p>{renderInline(block.text)}</p>;
  }
}
