/**
 * Heroicons adapter.
 *
 * Maps each canonical design system icon name to its Heroicons React component
 * for both outline and solid styles. Named imports enable tree-shaking.
 *
 * The Vite plugin (packages/react-vite) will alias this entire module to an
 * empty stub when Heroicons is not the selected library.
 */

import {
  ArrowDownIcon as ArrowDownOutline,
  ArrowLeftIcon as ArrowLeftOutline,
  ArrowRightIcon as ArrowRightOutline,
  ArrowUpIcon as ArrowUpOutline,
  ArrowTopRightOnSquareIcon as ExternalLinkOutline,
  ArrowDownTrayIcon as DownloadOutline,
  ArrowUpTrayIcon as UploadOutline,
  ArrowPathIcon as RefreshOutline,
  ArrowUturnLeftIcon as UndoOutline,
  ArrowUturnRightIcon as RedoOutline,
  BookmarkIcon as BookmarkOutline,
  BarsArrowUpIcon as SortAscOutline,
  BarsArrowDownIcon as SortDescOutline,
  Bars3Icon as MenuOutline,
  CalendarIcon as CalendarOutline,
  CheckIcon as CheckOutline,
  CheckCircleIcon as CheckCircleOutline,
  ChevronDownIcon as ChevronDownOutline,
  ChevronLeftIcon as ChevronLeftOutline,
  ChevronRightIcon as ChevronRightOutline,
  ChevronUpIcon as ChevronUpOutline,
  ClockIcon as ClockOutline,
  Cog6ToothIcon as SettingsOutline,
  DocumentDuplicateIcon as CopyOutline,
  DocumentIcon as FileOutline,
  EnvelopeIcon as MailOutline,
  EyeDropperIcon as PipetteOutline,
  ExclamationCircleIcon as AlertCircleOutline,
  ExclamationTriangleIcon as AlertTriangleOutline,
  EyeIcon as EyeOutline,
  EyeSlashIcon as EyeOffOutline,
  FolderIcon as FolderOutline,
  FunnelIcon as FilterOutline,
  HeartIcon as HeartOutline,
  HomeIcon as HomeOutline,
  InformationCircleIcon as InfoOutline,
  ListBulletIcon as ListOutline,
  LockClosedIcon as LockOutline,
  LockOpenIcon as UnlockOutline,
  MagnifyingGlassIcon as SearchOutline,
  MinusIcon as MinusOutline,
  PauseIcon as PauseOutline,
  PencilIcon as EditOutline,
  PhoneIcon as PhoneOutline,
  PlayIcon as PlayOutline,
  PlusIcon as PlusOutline,
  Squares2X2Icon as GridOutline,
  StarIcon as StarOutline,
  TagIcon as TagOutline,
  TrashIcon as TrashOutline,
  UserIcon as UserOutline,
  UsersIcon as UsersOutline,
  XMarkIcon as CloseOutline,
} from "@heroicons/react/24/outline";

import {
  ArrowDownIcon as ArrowDownSolid,
  ArrowLeftIcon as ArrowLeftSolid,
  ArrowRightIcon as ArrowRightSolid,
  ArrowUpIcon as ArrowUpSolid,
  ArrowTopRightOnSquareIcon as ExternalLinkSolid,
  ArrowDownTrayIcon as DownloadSolid,
  ArrowUpTrayIcon as UploadSolid,
  ArrowPathIcon as RefreshSolid,
  ArrowUturnLeftIcon as UndoSolid,
  ArrowUturnRightIcon as RedoSolid,
  BookmarkIcon as BookmarkSolid,
  BarsArrowUpIcon as SortAscSolid,
  BarsArrowDownIcon as SortDescSolid,
  Bars3Icon as MenuSolid,
  CalendarIcon as CalendarSolid,
  CheckIcon as CheckSolid,
  CheckCircleIcon as CheckCircleSolid,
  ChevronDownIcon as ChevronDownSolid,
  ChevronLeftIcon as ChevronLeftSolid,
  ChevronRightIcon as ChevronRightSolid,
  ChevronUpIcon as ChevronUpSolid,
  ClockIcon as ClockSolid,
  Cog6ToothIcon as SettingsSolid,
  DocumentDuplicateIcon as CopySolid,
  DocumentIcon as FileSolid,
  EnvelopeIcon as MailSolid,
  EyeDropperIcon as PipetteSolid,
  ExclamationCircleIcon as AlertCircleSolid,
  ExclamationTriangleIcon as AlertTriangleSolid,
  EyeIcon as EyeSolid,
  EyeSlashIcon as EyeOffSolid,
  FolderIcon as FolderSolid,
  FunnelIcon as FilterSolid,
  HeartIcon as HeartSolid,
  HomeIcon as HomeSolid,
  InformationCircleIcon as InfoSolid,
  ListBulletIcon as ListSolid,
  LockClosedIcon as LockSolid,
  LockOpenIcon as UnlockSolid,
  MagnifyingGlassIcon as SearchSolid,
  MinusIcon as MinusSolid,
  PauseIcon as PauseSolid,
  PencilIcon as EditSolid,
  PhoneIcon as PhoneSolid,
  PlayIcon as PlaySolid,
  PlusIcon as PlusSolid,
  Squares2X2Icon as GridSolid,
  StarIcon as StarSolid,
  TagIcon as TagSolid,
  TrashIcon as TrashSolid,
  UserIcon as UserSolid,
  UsersIcon as UsersSolid,
  XMarkIcon as CloseSolid,
} from "@heroicons/react/24/solid";

import type { CanonicalIconName } from "@ui-organized/utils";
import type { ComponentType } from "react";

export const heroiconsOutlineSet: Record<CanonicalIconName, ComponentType<any>> = {
  "chevron-down": ChevronDownOutline,
  "chevron-up": ChevronUpOutline,
  "chevron-left": ChevronLeftOutline,
  "chevron-right": ChevronRightOutline,
  "arrow-left": ArrowLeftOutline,
  "arrow-right": ArrowRightOutline,
  "arrow-up": ArrowUpOutline,
  "arrow-down": ArrowDownOutline,
  "external-link": ExternalLinkOutline,
  close: CloseOutline,
  check: CheckOutline,
  plus: PlusOutline,
  minus: MinusOutline,
  copy: CopyOutline,
  edit: EditOutline,
  trash: TrashOutline,
  download: DownloadOutline,
  upload: UploadOutline,
  refresh: RefreshOutline,
  undo: UndoOutline,
  redo: RedoOutline,
  "sort-asc": SortAscOutline,
  "sort-desc": SortDescOutline,
  filter: FilterOutline,
  sort: SortDescOutline,
  "check-circle": CheckCircleOutline,
  "alert-circle": AlertCircleOutline,
  "alert-triangle": AlertTriangleOutline,
  info: InfoOutline,
  loader: RefreshOutline,
  search: SearchOutline,
  eye: EyeOutline,
  "eye-off": EyeOffOutline,
  bookmark: BookmarkOutline,
  star: StarOutline,
  heart: HeartOutline,
  tag: TagOutline,
  menu: MenuOutline,
  grid: GridOutline,
  list: ListOutline,
  file: FileOutline,
  folder: FolderOutline,
  play: PlayOutline,
  pause: PauseOutline,
  user: UserOutline,
  users: UsersOutline,
  lock: LockOutline,
  unlock: UnlockOutline,
  mail: MailOutline,
  phone: PhoneOutline,
  settings: SettingsOutline,
  home: HomeOutline,
  calendar: CalendarOutline,
  clock: ClockOutline,
  pipette: PipetteOutline,
  // Heroicons ships no clockwise-rotate glyph; ArrowPathIcon is the closest,
  // and already backs "refresh" and "loader" here for the same reason.
  "rotate-cw": RefreshOutline,
  "rotate-ccw": UndoOutline,
};

export const heroiconsSolidSet: Record<CanonicalIconName, ComponentType<any>> = {
  "chevron-down": ChevronDownSolid,
  "chevron-up": ChevronUpSolid,
  "chevron-left": ChevronLeftSolid,
  "chevron-right": ChevronRightSolid,
  "arrow-left": ArrowLeftSolid,
  "arrow-right": ArrowRightSolid,
  "arrow-up": ArrowUpSolid,
  "arrow-down": ArrowDownSolid,
  "external-link": ExternalLinkSolid,
  close: CloseSolid,
  check: CheckSolid,
  plus: PlusSolid,
  minus: MinusSolid,
  copy: CopySolid,
  edit: EditSolid,
  trash: TrashSolid,
  download: DownloadSolid,
  upload: UploadSolid,
  refresh: RefreshSolid,
  undo: UndoSolid,
  redo: RedoSolid,
  "sort-asc": SortAscSolid,
  "sort-desc": SortDescSolid,
  filter: FilterSolid,
  sort: SortDescSolid,
  "check-circle": CheckCircleSolid,
  "alert-circle": AlertCircleSolid,
  "alert-triangle": AlertTriangleSolid,
  info: InfoSolid,
  loader: RefreshSolid,
  search: SearchSolid,
  eye: EyeSolid,
  "eye-off": EyeOffSolid,
  bookmark: BookmarkSolid,
  star: StarSolid,
  heart: HeartSolid,
  tag: TagSolid,
  menu: MenuSolid,
  grid: GridSolid,
  list: ListSolid,
  file: FileSolid,
  folder: FolderSolid,
  play: PlaySolid,
  pause: PauseSolid,
  user: UserSolid,
  users: UsersSolid,
  lock: LockSolid,
  unlock: UnlockSolid,
  mail: MailSolid,
  phone: PhoneSolid,
  settings: SettingsSolid,
  home: HomeSolid,
  calendar: CalendarSolid,
  clock: ClockSolid,
  pipette: PipetteSolid,
  "rotate-cw": RefreshSolid,
  "rotate-ccw": UndoSolid,
};
