import JSZip from "jszip";
import { useBuilderStore } from "../state/themeState";
import { resolveSemanticColors } from "@ui-organized/utils";
import {
  computeTypographyVars,
  computeSpacingVars,
  computeRadiusVars,
  computeComponentTokenVars,
  computeControlHeightVars,
  type CSSVarMap,
} from "../utils/semanticMapping";
import { buildThemeJson, buildIconsModule, buildReadme } from "../utils/buildConfig";

// ─── CSS emit helpers ──────────────────────────────────────────────────────────

function block(selector: string, vars: CSSVarMap): string {
  const body = Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${body}\n}`;
}

// ─── Hook ───────────────────────────────────────────────────────────────────────

export interface ExportResult {
  ok: boolean;
  errors?: string[];
}

export function useExport() {
  const state = useBuilderStore();

  /**
   * Build a self-contained theme stylesheet from the current builder state.
   *
   * Layout mirrors the shipped library's variables.css:
   *   :root                 → dark semantic colors (default) + theme-independent
   *                           typography / spacing / radius / component tokens
   *   [data-theme="dark"]   → dark semantic colors (re-asserted for nesting)
   *   [data-theme="light"]  → light semantic colors
   *
   * All colors are resolved against the chosen brand and neutral families via
   * the same `resolveSemanticColors` source of truth used by the live preview.
   */
  function buildCss(): string {
    const colorOpts = {
      brandRamp: state.brandRamp,
      neutralRamp: state.neutralRamp,
      brandShade: state.brandShade,
    };
    const dark = resolveSemanticColors("dark", colorOpts);
    const light = resolveSemanticColors("light", colorOpts);

    const nonColor: CSSVarMap = {
      ...computeTypographyVars(
        state.headingFamily,
        state.bodyFamily,
        state.headingWeights,
        state.bodyWeights,
        state.typeScaleSteps,
        state.leadingSteps,
      ),
      ...computeSpacingVars(state.spacingScale),
      ...computeRadiusVars(state.borderRadius),
      ...computeComponentTokenVars(state.borderRadius, state.spacingScale),
      ...computeControlHeightVars(state.leadingSteps, state.spacingScale),
    };

    const header =
      `/* ${state.themeName || "My Theme"} — generated by the Design System builder.\n` +
      `   Brand: ${state.brandMode === "custom" ? `custom ${state.brandHex}` : state.brandFamily} · ` +
      `Neutral: ${state.neutralFamily} · Primary shade: ${state.brandShade} */\n`;

    return [
      header,
      block(":root", { ...dark, ...nonColor }),
      block('[data-theme="dark"]', dark),
      block('[data-theme="light"]', light),
    ].join("\n\n") + "\n";
  }

  const slug = (): string =>
    (state.themeName || "theme").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");

  function download(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  function exportConfig(): ExportResult {
    try {
      download(new Blob([buildCss()], { type: "text/css" }), `${slug()}.css`);
      return { ok: true };
    } catch (err) {
      return { ok: false, errors: [String(err)] };
    }
  }

  /**
   * Export the full theme config as a zip: the canonical DTCG `theme.json`
   * (code + Figma), the derived `theme.css` (web), the `icons.ts` IconProvider
   * snippet, and a README tying them together.
   */
  async function exportBundle(): Promise<ExportResult> {
    try {
      const cssName = `${slug()}.css`;
      const zip = new JSZip();
      zip.file("theme.json", buildThemeJson(state));
      zip.file(cssName, buildCss());
      zip.file("icons.ts", buildIconsModule(state));
      zip.file("README.md", buildReadme(state, cssName));
      const blob = await zip.generateAsync({ type: "blob" });
      download(blob, `${slug()}-theme.zip`);
      return { ok: true };
    } catch (err) {
      return { ok: false, errors: [String(err)] };
    }
  }

  return { exportConfig, exportBundle, buildCss };
}
