import { useBuilderStore } from "../state/themeState";
import { resolveSemanticColors } from "@ui-organized/utils";
import {
  computeTypographyVars,
  computeSpacingVars,
  computeRadiusVars,
  computeComponentTokenVars,
  type CSSVarMap,
} from "../utils/semanticMapping";

// ─── CSS emit helpers ──────────────────────────────────────────────────────────

function block(selector: string, vars: CSSVarMap): string {
  const body = Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${body}\n}`;
}

// ─── Hook ───────────────────────────────────────────────────────────────────────

export interface ExportResult {
  ok: boolean;
  errors?: string[];
}

export function useExport() {
  const state = useBuilderStore();

  /**
   * Build a self-contained theme stylesheet from the current builder state.
   *
   * Layout mirrors the shipped library's variables.css:
   *   :root                 → dark semantic colors (default) + theme-independent
   *                           typography / spacing / radius / component tokens
   *   [data-theme="dark"]   → dark semantic colors (re-asserted for nesting)
   *   [data-theme="light"]  → light semantic colors
   *
   * All colors are resolved against the chosen brand and neutral families via
   * the same `resolveSemanticColors` source of truth used by the live preview.
   */
  function buildCss(): string {
    const colorOpts = {
      brandRamp: state.brandRamp,
      neutralRamp: state.neutralRamp,
      brandShade: state.brandShade,
    };
    const dark = resolveSemanticColors("dark", colorOpts);
    const light = resolveSemanticColors("light", colorOpts);

    const nonColor: CSSVarMap = {
      ...computeTypographyVars(
        state.headingFamily,
        state.bodyFamily,
        state.headingWeights,
        state.bodyWeights,
        state.typeScaleSteps,
        state.headingLineHeight,
        state.bodyLineHeight,
      ),
      ...computeSpacingVars(state.spacingScale),
      ...computeRadiusVars(state.borderRadius),
      ...computeComponentTokenVars(state.borderRadius, state.spacingScale),
    };

    const header =
      `/* ${state.themeName || "My Theme"} — generated by the Design System builder.\n` +
      `   Brand: ${state.brandMode === "custom" ? `custom ${state.brandHex}` : state.brandFamily} · ` +
      `Neutral: ${state.neutralFamily} · Primary shade: ${state.brandShade} */\n`;

    return [
      header,
      block(":root", { ...dark, ...nonColor }),
      block('[data-theme="dark"]', dark),
      block('[data-theme="light"]', light),
    ].join("\n\n") + "\n";
  }

  function exportConfig(): ExportResult {
    try {
      const css = buildCss();
      const blob = new Blob([css], { type: "text/css" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${(state.themeName || "theme").toLowerCase().replace(/\s+/g, "-")}.css`;
      a.click();
      URL.revokeObjectURL(url);
      return { ok: true };
    } catch (err) {
      return { ok: false, errors: [String(err)] };
    }
  }

  return { exportConfig, buildCss };
}
