/**
 * Shared flat ESLint config — the base layer every workspace package extends.
 *
 * This package used to be CommonJS and was imported by nothing: no
 * `eslint.config.*` existed anywhere in the repo, so the ten packages declaring
 * `"lint": "eslint src/"` all failed with "could not find an eslint.config.js
 * file". That is why CI never ran lint. It is now ESM flat config, referenced by
 * the root `eslint.config.mjs`, and it actually runs.
 *
 * Rule philosophy: this is a first lint pass over a codebase that has never been
 * linted, and a gate nobody can get green is a gate everybody disables. So only
 * rules that catch real defects are errors. Stylistic concerns belong to
 * Prettier, which already owns formatting via `.prettierrc`.
 */
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import globals from "globals";

/** Build output, generated files, and vendored assets — never linted. */
export const ignores = [
  "**/node_modules/**",
  "**/dist/**",
  "**/storybook-static/**",
  "**/playwright-report/**",
  "**/test-results/**",
  "**/.quality/**",
  "**/.turbo/**",
  "**/.wrangler/**",
  "_site/**",
  "**/coverage/**",
  "packages/tokens/output/**",
  // Generated by scripts/generate-core-palette.mjs — regenerate, don't edit.
  "packages/tokens/src/generated/**",
  "**/*.d.ts",
];

/** @type {import("eslint").Linter.Config[]} */
const config = [
  { ignores },

  {
    files: ["**/*.{js,mjs,cjs,jsx,ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      ecmaVersion: 2023,
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { "@typescript-eslint": tsPlugin },
    rules: {
      // ── Correctness ──────────────────────────────────────────────────────
      // "except-parens" (the default) rather than "always": `while ((m =
      // re.exec(s)))` is the standard exec-loop idiom and the extra parens are
      // exactly the marker that says "yes, this assignment is deliberate".
      "no-cond-assign": ["error", "except-parens"],
      "no-constant-binary-expression": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-fallthrough": "error",
      "no-self-compare": "error",
      "no-template-curly-in-string": "error",
      "no-unreachable": "error",
      "no-unsafe-optional-chaining": "error",
      "use-isnan": "error",
      "valid-typeof": "error",

      // TypeScript owns undefined-variable analysis and understands types,
      // globals and declaration merging better than the core rule does.
      "no-undef": "off",
      "no-redeclare": "off",
      "@typescript-eslint/no-redeclare": "error",

      // ── Unused code ──────────────────────────────────────────────────────
      // Warn, not error: an unused import is untidy, not broken, and making it
      // fatal on the first pass buys nothing. `_`-prefixed args are the
      // conventional "deliberately ignored" marker and stay silent.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          ignoreRestSiblings: true,
        },
      ],

      // ── Hygiene ──────────────────────────────────────────────────────────
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "error",
      "no-var": "error",
      "prefer-const": ["warn", { destructuring: "all" }],
      eqeqeq: ["error", "always", { null: "ignore" }],
    },
  },

  // Build scripts, generators and config files are Node programs whose whole
  // job is to talk to the terminal.
  {
    files: [
      "scripts/**/*.{js,mjs,ts}",
      "**/scripts/**/*.{js,mjs,ts}",
      "**/*.config.{js,mjs,ts}",
      "**/.storybook/**/*.{ts,tsx}",
    ],
    languageOptions: { globals: globals.node },
    rules: { "no-console": "off" },
  },

  // Tests assert on things lint would otherwise flag as pointless.
  {
    files: ["**/*.test.{ts,tsx,mjs}", "**/test/**/*.{ts,tsx}", "**/*.spec.ts"],
    rules: { "no-console": "off", "@typescript-eslint/no-unused-vars": "off" },
  },
];

export default config;
