/**
 * GitHub write flow (Connect.md §4.6). Runs in the UI iframe (which has `fetch`).
 * The plugin NEVER commits to the base branch — every mapping change goes through a
 * branch + PR, routing it into the same review/contribution loop as the rest of
 * UI Organized.
 *
 * The PR-metadata builders (branch name, commit message, title, body) are pure and
 * exported for testing; the fetch orchestration composes them.
 */

import type { LatestHashes } from "@ui-organized/code-connect/browser";
import type { GhSettings } from "./messages.js";

/** Path of the scanner's latest-scan artifact, alongside the manifest. */
function latestScanPath(settings: GhSettings): string {
  return settings.manifestPath.replace(/[^/]+$/, "latest-hashes.json");
}

const API = "https://api.github.com";

// ─── Pure builders (unit-tested) ──────────────────────────────────────────────

/** Deterministic branch name; `stamp` is passed in so tests are stable. */
export function mappingBranchName(codeName: string, stamp: string | number): string {
  const slug = codeName.replace(/[^A-Za-z0-9]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase();
  return `figma-mapping/${slug}-${stamp}`;
}

export function commitMessage(codeName: string): string {
  return `chore(code-connect): map Figma component to ${codeName}`;
}

export function prTitle(codeName: string): string {
  return `Code Connect: map ${codeName}`;
}

export interface PrMeta {
  codeName: string;
  codePath: string;
  componentKey: string;
  nodeName: string;
}

export function prBody(meta: PrMeta): string {
  return [
    `Maps a Figma component to \`${meta.codeName}\` via UI Organized Code Connect.`,
    "",
    `- **Code component:** \`${meta.codeName}\` (\`${meta.codePath}\`)`,
    `- **Figma component:** ${meta.nodeName}`,
    `- **Component key:** \`${meta.componentKey}\``,
    "",
    "Only the entry's `figmaComponentKey` / `figmaComponentName` / `status` change.",
    "Generated by the Code Connect Figma plugin.",
  ].join("\n");
}

// ─── base64 (UTF-8 safe, works in browser + Node) ─────────────────────────────

function toBase64(text: string): string {
  const bytes = new TextEncoder().encode(text);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}

function fromBase64(b64: string): string {
  const bin = atob(b64.replace(/\s/g, ""));
  return new TextDecoder().decode(Uint8Array.from(bin, (c) => c.charCodeAt(0)));
}

function encodePath(path: string): string {
  return path.split("/").map(encodeURIComponent).join("/");
}

// ─── REST plumbing ────────────────────────────────────────────────────────────

async function gh<T>(settings: GhSettings, path: string, init?: RequestInit): Promise<T> {
  const res = await fetch(`${API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${settings.token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init?.body ? { "Content-Type": "application/json" } : {}),
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`GitHub ${init?.method ?? "GET"} ${path} → ${res.status}: ${detail.slice(0, 300)}`);
  }
  return (res.status === 204 ? undefined : await res.json()) as T;
}

const repoBase = (s: GhSettings) => `/repos/${s.owner}/${s.repo}`;

/** Read the manifest file: its text (decoded) and blob sha (needed to update it). */
export async function fetchManifestFile(settings: GhSettings): Promise<{ text: string; sha: string }> {
  const data = await gh<{ content: string; sha: string }>(
    settings,
    `${repoBase(settings)}/contents/${encodePath(settings.manifestPath)}?ref=${encodeURIComponent(settings.branch)}`,
  );
  return { text: fromBase64(data.content), sha: data.sha };
}

/**
 * Read the latest-scan artifact for staleness checks (§4.4, §8). Returns null if it
 * hasn't been published yet — staleness is then simply unavailable, not an error.
 */
export async function fetchLatestScan(settings: GhSettings): Promise<LatestHashes | null> {
  try {
    const data = await gh<{ content: string }>(
      settings,
      `${repoBase(settings)}/contents/${encodePath(latestScanPath(settings))}?ref=${encodeURIComponent(settings.branch)}`,
    );
    return JSON.parse(fromBase64(data.content)) as LatestHashes;
  } catch {
    return null;
  }
}

export interface OpenPrInput extends PrMeta {
  /** Full re-serialized manifest text to commit. */
  updatedText: string;
  /** Blob sha of the file being replaced (from {@link fetchManifestFile}). */
  sha: string;
  /** Timestamp for a unique branch name. */
  stamp: string | number;
}

/** Branch → commit the manifest change → open a PR. Returns the PR URL + number. */
export async function openMappingPr(
  settings: GhSettings,
  input: OpenPrInput,
): Promise<{ url: string; number: number; branch: string }> {
  const base = repoBase(settings);
  const branch = mappingBranchName(input.codeName, input.stamp);

  const ref = await gh<{ object: { sha: string } }>(
    settings,
    `${base}/git/ref/heads/${encodeURIComponent(settings.branch)}`,
  );

  await gh(settings, `${base}/git/refs`, {
    method: "POST",
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: ref.object.sha }),
  });

  await gh(settings, `${base}/contents/${encodePath(settings.manifestPath)}`, {
    method: "PUT",
    body: JSON.stringify({
      message: commitMessage(input.codeName),
      content: toBase64(input.updatedText),
      branch,
      sha: input.sha,
    }),
  });

  const pr = await gh<{ html_url: string; number: number }>(settings, `${base}/pulls`, {
    method: "POST",
    body: JSON.stringify({
      title: prTitle(input.codeName),
      head: branch,
      base: settings.branch,
      body: prBody(input),
    }),
  });

  return { url: pr.html_url, number: pr.number, branch };
}
