/**
 * Heroicons name maps.
 *
 * Each canonical design-system name to the SVG markup `@ng-icons/heroicons`
 * publishes for it. Written by hand, as React's are: `@ng-icons` derives its
 * export names from the upstream file names, which is close to but not the same
 * as the component names the React packages use — `Grid2X2`, `ArrowUpAZ` and
 * `Trash2` are exactly where a mechanical transform goes wrong.
 *
 * Named imports, so only the icons listed here reach a bundle; the pack itself
 * is a catalogue of thousands.
 */
import {
  heroArrowDown, heroArrowDownTray, heroArrowLeft, heroArrowPath, heroArrowRight,
  heroArrowTopRightOnSquare, heroArrowUp, heroArrowUpTray, heroArrowUturnLeft,
  heroArrowUturnRight, heroBars3, heroBarsArrowDown, heroBarsArrowUp, heroBookmark,
  heroCalendar, heroCheck, heroCheckCircle, heroChevronDown, heroChevronLeft, heroChevronRight,
  heroChevronUp, heroClock, heroCog6Tooth, heroDocument, heroDocumentDuplicate, heroEnvelope,
  heroExclamationCircle, heroExclamationTriangle, heroEye, heroEyeDropper, heroEyeSlash,
  heroFolder, heroFunnel, heroHeart, heroHome, heroInformationCircle, heroListBullet,
  heroLockClosed, heroLockOpen, heroMagnifyingGlass, heroMinus, heroPause, heroPencil,
  heroPhone, heroPlay, heroPlus, heroSquares2x2, heroStar, heroTag, heroTrash, heroUser,
  heroUsers, heroXMark,
} from "@ng-icons/heroicons/outline";
import {
  heroArrowDownSolid, heroArrowDownTraySolid, heroArrowLeftSolid, heroArrowPathSolid,
  heroArrowRightSolid, heroArrowTopRightOnSquareSolid, heroArrowUpSolid, heroArrowUpTraySolid,
  heroArrowUturnLeftSolid, heroArrowUturnRightSolid, heroBars3Solid, heroBarsArrowDownSolid,
  heroBarsArrowUpSolid, heroBookmarkSolid, heroCalendarSolid, heroCheckCircleSolid,
  heroCheckSolid, heroChevronDownSolid, heroChevronLeftSolid, heroChevronRightSolid,
  heroChevronUpSolid, heroClockSolid, heroCog6ToothSolid, heroDocumentDuplicateSolid,
  heroDocumentSolid, heroEnvelopeSolid, heroExclamationCircleSolid,
  heroExclamationTriangleSolid, heroEyeDropperSolid, heroEyeSlashSolid, heroEyeSolid,
  heroFolderSolid, heroFunnelSolid, heroHeartSolid, heroHomeSolid, heroInformationCircleSolid,
  heroListBulletSolid, heroLockClosedSolid, heroLockOpenSolid, heroMagnifyingGlassSolid,
  heroMinusSolid, heroPauseSolid, heroPencilSolid, heroPhoneSolid, heroPlaySolid, heroPlusSolid,
  heroSquares2x2Solid, heroStarSolid, heroTagSolid, heroTrashSolid, heroUserSolid,
  heroUsersSolid, heroXMarkSolid,
} from "@ng-icons/heroicons/solid";
import type { CanonicalIconName } from "@ui-organized/utils";

/**
 * Two substitutions carried over from the React adapter, for the same reason:
 * Heroicons ships no spinner and no clockwise-rotate glyph, so `loader` and
 * `rotate-cw` both use ArrowPath, which already backs `refresh`.
 */
export const heroiconsOutlineSet: Record<CanonicalIconName, string> = {
  "chevron-down":   heroChevronDown,
  "chevron-up":     heroChevronUp,
  "chevron-left":   heroChevronLeft,
  "chevron-right":  heroChevronRight,
  "arrow-left":     heroArrowLeft,
  "arrow-right":    heroArrowRight,
  "arrow-up":       heroArrowUp,
  "arrow-down":     heroArrowDown,
  "external-link":  heroArrowTopRightOnSquare,
  "close":          heroXMark,
  "check":          heroCheck,
  "plus":           heroPlus,
  "minus":          heroMinus,
  "copy":           heroDocumentDuplicate,
  "edit":           heroPencil,
  "trash":          heroTrash,
  "download":       heroArrowDownTray,
  "upload":         heroArrowUpTray,
  "refresh":        heroArrowPath,
  "undo":           heroArrowUturnLeft,
  "redo":           heroArrowUturnRight,
  "sort-asc":       heroBarsArrowUp,
  "sort-desc":      heroBarsArrowDown,
  "sort":           heroBarsArrowDown,
  "filter":         heroFunnel,
  "check-circle":   heroCheckCircle,
  "alert-circle":   heroExclamationCircle,
  "alert-triangle": heroExclamationTriangle,
  "info":           heroInformationCircle,
  "loader":         heroArrowPath,
  "search":         heroMagnifyingGlass,
  "eye":            heroEye,
  "eye-off":        heroEyeSlash,
  "bookmark":       heroBookmark,
  "star":           heroStar,
  "heart":          heroHeart,
  "tag":            heroTag,
  "menu":           heroBars3,
  "grid":           heroSquares2x2,
  "list":           heroListBullet,
  "file":           heroDocument,
  "folder":         heroFolder,
  "play":           heroPlay,
  "pause":          heroPause,
  "user":           heroUser,
  "users":          heroUsers,
  "lock":           heroLockClosed,
  "unlock":         heroLockOpen,
  "mail":           heroEnvelope,
  "phone":          heroPhone,
  "settings":       heroCog6Tooth,
  "home":           heroHome,
  "calendar":       heroCalendar,
  "clock":          heroClock,
  "pipette":        heroEyeDropper,
  "rotate-cw":      heroArrowPath,
  "rotate-ccw":     heroArrowUturnLeft,
};

export const heroiconsSolidSet: Record<CanonicalIconName, string> = {
  "chevron-down":   heroChevronDownSolid,
  "chevron-up":     heroChevronUpSolid,
  "chevron-left":   heroChevronLeftSolid,
  "chevron-right":  heroChevronRightSolid,
  "arrow-left":     heroArrowLeftSolid,
  "arrow-right":    heroArrowRightSolid,
  "arrow-up":       heroArrowUpSolid,
  "arrow-down":     heroArrowDownSolid,
  "external-link":  heroArrowTopRightOnSquareSolid,
  "close":          heroXMarkSolid,
  "check":          heroCheckSolid,
  "plus":           heroPlusSolid,
  "minus":          heroMinusSolid,
  "copy":           heroDocumentDuplicateSolid,
  "edit":           heroPencilSolid,
  "trash":          heroTrashSolid,
  "download":       heroArrowDownTraySolid,
  "upload":         heroArrowUpTraySolid,
  "refresh":        heroArrowPathSolid,
  "undo":           heroArrowUturnLeftSolid,
  "redo":           heroArrowUturnRightSolid,
  "sort-asc":       heroBarsArrowUpSolid,
  "sort-desc":      heroBarsArrowDownSolid,
  "sort":           heroBarsArrowDownSolid,
  "filter":         heroFunnelSolid,
  "check-circle":   heroCheckCircleSolid,
  "alert-circle":   heroExclamationCircleSolid,
  "alert-triangle": heroExclamationTriangleSolid,
  "info":           heroInformationCircleSolid,
  "loader":         heroArrowPathSolid,
  "search":         heroMagnifyingGlassSolid,
  "eye":            heroEyeSolid,
  "eye-off":        heroEyeSlashSolid,
  "bookmark":       heroBookmarkSolid,
  "star":           heroStarSolid,
  "heart":          heroHeartSolid,
  "tag":            heroTagSolid,
  "menu":           heroBars3Solid,
  "grid":           heroSquares2x2Solid,
  "list":           heroListBulletSolid,
  "file":           heroDocumentSolid,
  "folder":         heroFolderSolid,
  "play":           heroPlaySolid,
  "pause":          heroPauseSolid,
  "user":           heroUserSolid,
  "users":          heroUsersSolid,
  "lock":           heroLockClosedSolid,
  "unlock":         heroLockOpenSolid,
  "mail":           heroEnvelopeSolid,
  "phone":          heroPhoneSolid,
  "settings":       heroCog6ToothSolid,
  "home":           heroHomeSolid,
  "calendar":       heroCalendarSolid,
  "clock":          heroClockSolid,
  "pipette":        heroEyeDropperSolid,
  "rotate-cw":      heroArrowPathSolid,
  "rotate-ccw":     heroArrowUturnLeftSolid,
};
